package com._520it.crm.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2018-06-23T17:05:18.113+08:00
 * Generated source version: 3.0.9
 * 
 */
@WebService(targetNamespace = "http://webservice.crm._520it.com/", name = "ICaculateService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ICaculateService {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://webservice.crm._520it.com/", partName = "return")
    public int getSum(
        @WebParam(partName = "arg0", name = "arg0")
        int arg0,
        @WebParam(partName = "arg1", name = "arg1")
        int arg1
    );
}
